// Per-team accent color + flag emoji, keyed by FIFA code.
// England/Scotland use the GB subdivision flag sequences.

export const TEAMS = {
  MEX: { color: "#0b6b48", flag: "🇲🇽" },
  RSA: { color: "#e8b923", flag: "🇿🇦" },
  KOR: { color: "#cd2e3a", flag: "🇰🇷" },
  CZE: { color: "#d7141a", flag: "🇨🇿" },
  CAN: { color: "#d52b1e", flag: "🇨🇦" },
  BIH: { color: "#002f6c", flag: "🇧🇦" },
  QAT: { color: "#8a1538", flag: "🇶🇦" },
  SUI: { color: "#d52b1e", flag: "🇨🇭" },
  BRA: { color: "#ffdf00", flag: "🇧🇷" },
  MAR: { color: "#c1272d", flag: "🇲🇦" },
  HAI: { color: "#00209f", flag: "🇭🇹" },
  SCO: { color: "#0065bf", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  USA: { color: "#3c3b6e", flag: "🇺🇸" },
  PAR: { color: "#d52b1e", flag: "🇵🇾" },
  AUS: { color: "#ffc726", flag: "🇦🇺" },
  TUR: { color: "#e30a17", flag: "🇹🇷" },
  GER: { color: "#ffce00", flag: "🇩🇪" },
  CUW: { color: "#002b7f", flag: "🇨🇼" },
  CIV: { color: "#f77f00", flag: "🇨🇮" },
  ECU: { color: "#ffd100", flag: "🇪🇨" },
  NED: { color: "#ff6f00", flag: "🇳🇱" },
  JPN: { color: "#bc002d", flag: "🇯🇵" },
  SWE: { color: "#fecc02", flag: "🇸🇪" },
  TUN: { color: "#e70013", flag: "🇹🇳" },
  BEL: { color: "#fdda24", flag: "🇧🇪" },
  EGY: { color: "#ce1126", flag: "🇪🇬" },
  IRN: { color: "#239f40", flag: "🇮🇷" },
  NZL: { color: "#9aa6ba", flag: "🇳🇿" },
  ESP: { color: "#c60b1e", flag: "🇪🇸" },
  CPV: { color: "#003893", flag: "🇨🇻" },
  KSA: { color: "#006c35", flag: "🇸🇦" },
  URU: { color: "#7da7d8", flag: "🇺🇾" },
  FRA: { color: "#0055a4", flag: "🇫🇷" },
  SEN: { color: "#00853f", flag: "🇸🇳" },
  IRQ: { color: "#ce1126", flag: "🇮🇶" },
  NOR: { color: "#ba0c2f", flag: "🇳🇴" },
  ARG: { color: "#75aadb", flag: "🇦🇷" },
  ALG: { color: "#006233", flag: "🇩🇿" },
  AUT: { color: "#ed2939", flag: "🇦🇹" },
  JOR: { color: "#ce1126", flag: "🇯🇴" },
  POR: { color: "#046a38", flag: "🇵🇹" },
  COD: { color: "#007fff", flag: "🇨🇩" },
  UZB: { color: "#1eb53a", flag: "🇺🇿" },
  COL: { color: "#fcd116", flag: "🇨🇴" },
  ENG: { color: "#cf081f", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  CRO: { color: "#171796", flag: "🇭🇷" },
  GHA: { color: "#fcd116", flag: "🇬🇭" },
  PAN: { color: "#da121a", flag: "🇵🇦" },
};

export const teamColor = (code) => TEAMS[code]?.color ?? "#5d6b82";
export const teamFlag = (code) => TEAMS[code]?.flag ?? "⚽";
